apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caerora
spec:
  tls:
    - hosts:
        - caerora.com
        - www.caerora.com
      secretName: caerora-tls
  rules:
    - host: caerora.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
    - host: www.caerora.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
