# Generated by Django 5.0.6 on 2026-07-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image_product_supplier_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single-unit cost from the supplier (internal, for margin tracking).', max_digits=10, null=True),
        ),
    ]
