# Generated by Django 5.0.6 on 2026-06-29 12:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('countries', models.TextField(help_text='Comma-separated ISO country codes (e.g. DE,FR,NL). Use * for rest of world.')),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax percentage applied to subtotal (e.g. 21.00 for 21% VAT).', max_digits=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_over', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_estimate', models.CharField(blank=True, help_text="e.g. '2-4 business days'", max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ('position', 'price'),
            },
        ),
    ]
