# Generated by Django 5.0.6 on 2026-07-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_bar_text', models.CharField(blank=True, max_length=200)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_title', models.CharField(blank=True, max_length=120)),
                ('hero_title_accent', models.CharField(blank=True, max_length=120)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_cta_label', models.CharField(blank=True, max_length=60)),
                ('hero_cta_href', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('brand_band_title', models.CharField(blank=True, max_length=160)),
                ('brand_band_body', models.TextField(blank=True)),
                ('brand_band_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('newsletter_title', models.CharField(blank=True, max_length=160)),
                ('newsletter_body', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('handle', models.CharField(blank=True, help_text='e.g. @handle or a location/title.', max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5 stars.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', '-created_at'),
            },
        ),
    ]
