# Generated by Django 5.0.6 on 2026-06-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('view_item_list', 'View product list'), ('select_item', 'Click product (CTR)'), ('view_item', 'View product'), ('product_dwell', 'Product time-on-page'), ('add_to_cart', 'Add to cart'), ('begin_checkout', 'Begin checkout'), ('add_shipping_info', 'Add shipping info'), ('add_payment_info', 'Add payment info'), ('purchase', 'Purchase'), ('newsletter_signup', 'Newsletter signup')], db_index=True, max_length=32)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('dwell_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=160)),
                ('utm_term', models.CharField(blank=True, max_length=160)),
                ('utm_content', models.CharField(blank=True, max_length=160)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'), models.Index(fields=['utm_source', 'utm_campaign'], name='analytics_e_utm_sou_06f9f0_idx')],
            },
        ),
    ]
