# Generated by Django 5.0.6 on 2026-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page view'), ('view_item_list', 'View product list'), ('select_item', 'Click product (CTR)'), ('view_item', 'View product'), ('product_dwell', 'Product time-on-page'), ('add_to_cart', 'Add to cart'), ('begin_checkout', 'Begin checkout'), ('add_shipping_info', 'Add shipping info'), ('add_payment_info', 'Add payment info'), ('purchase', 'Purchase'), ('newsletter_signup', 'Newsletter signup'), ('search', 'Site search')], db_index=True, max_length=32),
        ),
    ]
