apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: caerora
    includeSelectors: false

resources:
  - pvcs.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - nginx.yaml
  - migrate-job.yaml
  - ingress.yaml

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.k8s.conf

generatorOptions:
  disableNameSuffixHash: true
